version: "3.7"

services:
  mongodb:
    build: ./mongo
    container_name: burrobot-mongodb
    image: burrobot-mongodb:1.0
    env_file:
      - ./mongo/mongodb.env
    networks:
      burrobot-network:
        aliases:
          - burrobot-mongodb
    ports:
      - "14000:27017"
    volumes:
      - type: volume
        source: burrobot-mongodb
        target: /data/db
    healthcheck:
      test: "[ `echo 'db.runCommand(\"ping\").ok' | mongo localhost/example-database --quiet` ] && echo 0 || echo 1"
      interval: 5s
      start_period: 10s
      timeout: 4s
      retries: 3

  mysqldb:
    build: ./mysql
    container_name: burrobot-mysqldb
    image: burrobot-mysqldb:1.0
    env_file:
      - ./mysql/mysqldb.env
    networks:
      burrobot-network:
        aliases:
          - burrobot-mysqldb
    ports:
      - "14001:3306"
      - "14002:33060"
    volumes:
      - type: volume
        source: burrobot-mysqldb
        target: /data/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      start_period: 10s
      timeout: 4s
      retries: 3

networks:
  burrobot-network:
    name: burrobot-network
    driver: bridge
    ipam:
      config:
        - subnet: 169.10.10.0/24

volumes:
  burrobot-mongodb:
    name: burrobot-mongodb
  burrobot-mysqldb:
    name: burrobot-mysqldb